### ISSUE TITLE
load libraries *declare*d in -meta file

### ISSUE THREAD

**Issue by umlaeute** [pure-data/libdir#2]
it would be great if the `libdir` mechanism could support multi-binary libraries better.

e.g. right now `Gem` duplicates quite some code from `libdir` (searching for a specially named file and adding the path to it), but still requires for the actual `Gem.dll` to be dlopen()ed.

it would be great if a libdir-loaded `Gem` would make sure that the `Gem.dll` is opened as well.

### draft
i think this could work, if libdir could do some additional steps:
- [x] check for meta-file
- [x] add the path to meta-file to the canvas-local search path
- [ ] parse the meta-file for `declare` lines
- [ ] load any libs (and add paths) mentioned in `declare`.

in practice this is not trivial (my feeble attempts to implement this failed so far)
